Repository GSG-G13/Mohannad-Mohammed, pull requests merged in 2023-03, with the labels that each got.

#1 adding assets files
  code.js
  index.html
  style.css
Labels: Starting Project, cheack

#2 testing
  index.html
Labels: test

#8 finalTest
  index.html
Labels: cheack

#9 Finalizing our Project
  .vscode/settings.json
  css/style-1.css
  index.html
  js/module-1.js
Labels: done

#11 fix display bugs
  css/style-1.css
  index.html
  js/module-1.js
  js/module-2.js
  js/sss.js
Labels: fixing
